apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
  labels:
    app: traefik-ingress
data:
  traefik.yml: |
    # Global settings
    entryPoints:
      http:
        address: :80
  
      https:
        address: :443

    api:
      insecure: true
    
    providers:
      kubernetesCRD: {}
