apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:2.1
          volumeMounts:
            - name: traefik-config
              mountPath: /etc/traefik/
          ports:
            - name: http
              containerPort: 80
            - name: traefik
              containerPort: 8080
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-config
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik

spec:
  selector:
    app: traefik
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  - name: traefik
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30888
